/**
 * Mermaid element id parsing utilities.
 *
 * Mermaid ids are generated by backend mapping (see netbox-to-mermaid.yaml) and follow patterns like:
 * - region_<id>
 * - site_<id>
 * - device_<id>
 * - if_<id>
 * - attr_<mermaidId> (attribute/comment node that belongs to the owning element)
 */

const KNOWN_ENTITIES = new Set([
  // Organization
  'region',
  'site-group',
  'site',
  'location',
  'tenant-group',
  'tenant',

  // Inventory / Definitions
  'manufacturer',
  'device-role',
  'platform',
  'device-type',
  'virtual-chassis',
  'rack-type',
  'rack-role',

  // Infrastructure
  'rack',
  'device',
  'if',
  'container',
  'node',
])

const ROOT_IDS = new Set(['definitions', 'infrastructure', 'connections'])

/**
 * @param {string} mermaidId
 * @returns {string}
 */
export function normalizeMermaidId(mermaidId) {
  if (typeof mermaidId !== 'string') return ''
  const trimmed = mermaidId.trim()
  if (!trimmed) return ''
  let base = trimmed.startsWith('attr_') ? trimmed.slice('attr_'.length) : trimmed

  // Mermaid sometimes appends internal suffixes like "-label"/"-text" to ids.
  base = base.replace(/-(label|text).*$/, '')

  // Some entities have hyphens in the model key, but Mermaid identifiers are safest
  // with underscores. Normalize known prefixes back to the domain entity name.
  const mermaidToDomain = new Map([
    ['site_group', 'site-group'],
    ['tenant_group', 'tenant-group'],
    ['device_role', 'device-role'],
    ['device_type', 'device-type'],
    ['virtual_chassis', 'virtual-chassis'],
    ['rack_type', 'rack-type'],
    ['rack_role', 'rack-role'],
  ])

  for (const [mermaidPrefix, domainEntity] of mermaidToDomain.entries()) {
    const prefix = `${mermaidPrefix}_`
    if (base.startsWith(prefix)) {
      base = `${domainEntity}_${base.slice(prefix.length)}`
      break
    }
  }

  return base
}

/**
 * Parses a Mermaid id to a domain reference.
 *
 * @param {string} mermaidId
 * @returns {{ entity: string, id: string } | null}
 */
export function parseMermaidDomainRef(mermaidId) {
  const base = normalizeMermaidId(mermaidId)
  if (!base) return null

  if (ROOT_IDS.has(base)) {
    return { entity: 'root', id: base }
  }

  // Entity prefixes may contain underscores (e.g. device_role_123). Split on the last
  // underscore so ids remain intact and entity is parsed correctly.
  const idx = base.lastIndexOf('_')
  if (idx <= 0 || idx === base.length - 1) return null

  const entity = base.slice(0, idx)
  const id = base.slice(idx + 1)

  if (!KNOWN_ENTITIES.has(entity)) return null
  if (!id.trim()) return null

  return { entity, id }
}
