/**
 * Mermaid element id parsing utilities.
 *
 * Mermaid ids are generated by backend mapping (see netbox-to-mermaid.yaml) and follow patterns like:
 * - region_<id>
 * - site_<id>
 * - device_<id>
 * - if_<id>
 * - attr_<mermaidId> (attribute/comment node that belongs to the owning element)
 */

const KNOWN_ENTITIES = new Set([
  'region',
  'site-group',
  'site',
  'location',
  'rack',
  'device',
  'if',
  'container',
  'node',
])

const ROOT_IDS = new Set(['definitions', 'infrastructure', 'connections'])

/**
 * @param {string} mermaidId
 * @returns {string}
 */
export function normalizeMermaidId(mermaidId) {
  if (typeof mermaidId !== 'string') return ''
  const trimmed = mermaidId.trim()
  if (!trimmed) return ''
  const withoutPrefix = trimmed.startsWith('attr_') ? trimmed.slice('attr_'.length) : trimmed

  // Some entities have hyphens in the NetBox model key, but Mermaid identifiers are
  // safest with underscores. Normalize known cases back to the domain entity name.
  const normalizedEntity = withoutPrefix.replace(/^site_group_/, 'site-group_')

  // Mermaid sometimes appends internal suffixes like "-label"/"-text" to ids.
  // Domain object ids are stable hex strings (see backend DiagramDomainStore).
  const m = normalizedEntity.match(/^(region|site-group|site|location|rack|device|if|container|node)_([A-Za-z0-9]+)/)
  if (m) return `${m[1]}_${m[2]}`

  return normalizedEntity
}

/**
 * Parses a Mermaid id to a domain reference.
 *
 * @param {string} mermaidId
 * @returns {{ entity: string, id: string } | null}
 */
export function parseMermaidDomainRef(mermaidId) {
  const base = normalizeMermaidId(mermaidId)
  if (!base) return null

  if (ROOT_IDS.has(base)) {
    return { entity: 'root', id: base }
  }

  const idx = base.indexOf('_')
  if (idx <= 0 || idx === base.length - 1) return null

  const entity = base.slice(0, idx)
  const id = base.slice(idx + 1)

  if (!KNOWN_ENTITIES.has(entity)) return null
  if (!id.trim()) return null

  return { entity, id }
}
